version: 2

models:
    
  - name: stg_customers
    description :  "{{ doc('src_customers') }}"
  - name: stg_order_items
    description :  "{{ doc('src_order_items') }}"
    columns : 
      - name : order_id
        description : "{{ doc('order_id')}}"
        tests : 
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name : product_id
        description : "{{ doc('product_id')}}"
        tests : 
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name : list_based_amount
        description : "{{ doc('list_based_amount') }}"
      - name : billed_amount
        description : "{{ doc('billed_amount') }}"
      - name : discount_amount
        description : "{{ doc('discount_amount') }}"
  - name: stg_orders
    description :  "{{ doc('src_orders') }}"
    columns : 
      - name : customer_id
        description : "{{ doc('customer_id')}}"
        tests : 
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name : store_id
        description : "{{ doc('store_id')}}"
        tests : 
          - relationships:
              to: ref('stg_stores')
              field: store_id
      - name : staff_id
        description : "{{ doc('staff_id')}}"
        tests : 
          - relationships:
              to: ref('stg_staffs')
              field: staff_id
      - name : order_date
        description : "{{ doc('order_date') }}"
      - name : order_date_year
        description : "{{ doc('order_date_year') }}"
      - name : order_date_month
        description : "{{ doc('order_date_month') }}"
      - name : order_date_weekday
        description : "{{ doc('order_date_weekday') }}"
      - name : shipping_delay
        description : "{{ doc('shipping_delay') }}"
      - name : order_status
        description : "{{ doc('order_status') }}"
        tests : 
          - accepted_values : 
              values : [1, 2, 3, 4]
              quote: false

  - name: stg_products
    description :  "{{ doc('src_products') }}"

  - name: stg_staffs
    description :  "{{ doc('src_staffs') }}"
    columns: 
      - name : active
        description : "{{ doc('active') }}"
        tests :
          - accepted_values :
              values : [0, 1]
              quote: false

  - name: stg_stocks
    description :  "{{ doc('src_stocks') }}"

  - name: stg_stores
    description :  "{{ doc('src_stores') }}"
