version: 2

models:
    
  - name: mart_staff_performance_last_month
    description : "{{ doc('mart_t__staff_performance_last_month') }}"
    columns:
      # Dimensions
      - name: staff_id
        description: "{{ doc('f_staff_id') }}"
        data_type: integer
      - name: first_name
        description: "{{ doc('f_first_name') }}"
        data_type: string
      - name: last_name
        description: "{{ doc('f_last_name') }}"
        data_type: string
      - name: store_id
        description: "{{ doc('f_store_id') }}"
        data_type: integer
      - name: store_name
        description: "{{ doc('f_store_name') }}"
        data_type: string
      - name: order_date_year
        description: "{{ doc('f_order_date_year') }}"
        data_type: int64
      - name: order_date_month
        description: "{{ doc('f_order_date_month') }}"
        data_type: int64
      - name: orders_total
        description : "{{ doc('f_orders_total') }}"
        data_type: int64
     # Metrics
      - name: list_base_value_sum
        description : "{{ doc('f_list_base_value_sum') }}"
        data_type: float64
      - name: revenue_sum
        description : "{{ doc('f_revenue_sum') }}"
        data_type: float64
      - name: average_discount_ratio
        description : "{{ doc('f_average_discount_ratio') }}"
        data_type: float64
      - name: avg_revenue_per_order
        description : "{{ doc('f_avg_revenue_per_order') }}"
        data_type: float64

  - name : mart_stores_performance_last_month
    description : "{{ doc('mart_t__staff_performance_last_month') }}"
    columns:
      # Dimensions
      - name: store_name
        description: "{{ doc('f_store_name') }}"
        data_type: string
      - name: store_state
        description: "{{ doc('f_store_state') }}"
        data_type: string
      - name: store_zip_code
        description: "{{ doc('f_store_zip_code') }}"
        data_type: int64
      - name: store_city
        description: "{{ doc('f_store_city') }}"
        data_type: string
      - name: order_date_year
        description: "{{ doc('f_order_date_year') }}"
        data_type: int64
      - name: order_date_month
        description: "{{ doc('f_order_date_month') }}"
        data_type: int64
      # Metrics
      - name: orders_total
        description : "{{ doc('f_orders_total') }}"
        data_type: int64
      - name: distinct_customers_total
        description : "{{ doc('f_distinct_customers_total') }}"
        data_type: int64
      - name: selled_products_total
        description : "{{ doc('f_selled_products_total') }}"
        data_type: int64
      - name: list_base_value_sum
        description : "{{ doc('f_list_base_value_sum') }}"
        data_type: float64
      - name: revenue_sum
        description : "{{ doc('f_revenue_sum') }}"
        data_type: float64

  - name : mart_stores_performance
    description : "{{ doc('mart_t__stores_performance') }}"
    columns:
      # Dimensions
      - name: store_name
        description: "{{ doc('f_store_name') }}"
        data_type: string
      - name: store_state
        description: "{{ doc('f_store_state') }}"
        data_type: string
      - name: store_zip_code
        description: "{{ doc('f_store_zip_code') }}"
        data_type: int64
      - name: store_city
        description: "{{ doc('f_store_city') }}"
        data_type: string
      - name: order_date
        description: "{{ doc('f_order_date') }}"
        data_type: date
      - name: order_date_year
        description: "{{ doc('f_order_date_year') }}"
        data_type: int64
      - name: order_date_month
        description: "{{ doc('f_order_date_month') }}"
        data_type: int64
      - name: order_date_weekday
        description : "{{ doc('f_order_date_weekday') }}"
        data_type: int64
      - name: category_name
        description : "{{ doc('f_category_name') }}"
        data_type: string
      - name: brand_name
        description : "{{ doc('f_brand_name') }}"
        data_type: string
      - name: product_name
        description : "{{ doc('f_product_name') }}"
        data_type: string
      # Metrics
      - name: orders_total
        description : "{{ doc('f_orders_total') }}"
        data_type: int64
      - name: distinct_customers_total
        description : "{{ doc('f_distinct_customers_total') }}"
        data_type: int64
      - name: selled_products_total
        description : "{{ doc('f_selled_products_total') }}"
        data_type: int64
      - name: list_base_value_sum
        description : "{{ doc('f_list_base_value_sum') }}"
        data_type: float64
      - name: revenue_sum
        description : "{{ doc('f_revenue_sum') }}"
        data_type: float64
